# permissions for end users to edit k6suites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k6suite-editor-role
rules:
- apiGroups:
  - k6.io
  resources:
  - k6suites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k6.io
  resources:
  - k6suites/status
  verbs:
  - get
